pipeline:
  build:
    image: mazzolino/docker-compose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose build
      - docker-compose run web rake test
      - docker-compose rm -f -v
