pipeline:
  build:
    image: mazzolino/docker-compose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - mkdir /root/.ssh && echo "$SSH_KEY" >/root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
      - echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >>/root/.ssh/known_hosts
      - apk add --no-cache openssh-client && ssh -v -o StrictHostKeyChecking=yes git@github.com
      - docker-compose build ci
      - docker-compose run --rm ci
      - docker-compose down --volumes --remove-orphans
