version: '2'
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres

  dev:
    extends:
      service: app
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:9.3
