version: '2'
services:
  app:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres

  dev:
    extends:
      service: app
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/usr/src/app
    environment:
      DB_NAME: dev
    depends_on:
      - db

  test:
    extends:
      service: app
    command: rake test
    volumes:
      - .:/usr/src/app
    environment:
      DB_NAME: test
    depends_on:
      - db

  ci:
    extends:
      service: app
    command: rake test
    depends_on:
      - db

  db:
    image: postgres:9.3
